### ISSUE TITLE
Changing reading options doesn't change current article

### ISSUE THREAD

**Issue by deweytyl** [GrinnellAppDev/SandB-iOS#15]
The Reading Options (controlling font and font size) have no effect. Nothing crashes, but nothing happens.

Still need to investigate extent. Does this feature not work in previous versions of iOS? Does the app crash in iOS 8? Who knows.

Spotted in f305086

**Comment by alexthemitchell** [comment]
It's my understanding that they take effect when the next article loads. Probably something in the 'viewDidLoad.' A good first bug.
