### ISSUE TITLE
"Favorite" button automatically selects when view is scrolled

### ISSUE THREAD

**Issue by alexthemitchell** [GrinnellAppDev/SandB-iOS#17]
- Scrolling so that the navbar is below the picture causes the "favorite" icon to change to a golden color
- Also, the "favorite" star button adds to "saved articles." Perhaps the icon or the folder name should be changed for consistency.

**Comment by deweytyl** [comment]
Fixed in 33bc6ab93cecdc339d40955d070e6410ac33941c
